[parity]
chain = "streamr-spec.json"
base_path = "./parity1"
[network]
port = 30301
allow_ips = "all"
nat = "0.0.0.0"
reserved_only = true
reserved_peers = "./peers"
[rpc]
interface = "all"
port = 8541
apis = ["all"]
cors = ["all"]
[websockets]
interface = "all"
port = 8451
origins = ["all"]
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
