[parity]
chain = "streamr-spec.json"
base_path = "./parity_data"
[network]
port = 30309
allow_ips = "all"
nat = "0.0.0.0"
[rpc]
interface = "all"
port = 8540
apis = ["all"]
cors = ["all"]
hosts = ["all"]
[websockets]
interface = "all"
port = 8450
origins = ["all"]
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "all"
reseal_min_period = 2000
reseal_max_period = 3000
min_gas_price = 1000000000
