[parity]
chain = "streamr-spec.json"
base_path = "./parity2"
[network]
port = 30302
allow_ips = "all"
nat = "0.0.0.0"
reserved_only = true
reserved_peers = "./peers"
[rpc]
interface = "all"
port = 8542
apis = ["all"]
cors = ["all"]
hosts = ["all"]
[websockets]
interface = "all"
port = 8452
origins = ["all"]
hosts = ["all"]
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x002e28950558fbede1a9675cb113f0bd20912019"
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000